F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>code .

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>pt one.py
'pt' is not recognized as an internal or external command,
operable program or batch file.

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py one.py
10
15
102
171

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>code .

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py two.py
0b1010
0b1010
0b1010
0b1010

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py three.py
10
10
10
10

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>


Microsoft Windows [Version 10.0.26100.4061]
(c) Microsoft Corporation. All rights reserved.

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py one.py
10
15
102
171

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py two.py
0b1010
0b1010
0b1010
0b1010

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py three.py
10
10
10
10
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>








F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py four.py
15
0b1111
10

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py five.py
10
15
10
10

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py six.py
10
(10, 20)
<class 'int'>
<class 'tuple'>

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py seven.py
10
20
30

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>py eight.py
[101, 102, 103, 104]
101
102
103
104
Traceback (most recent call last):
  File "F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION\eight.py", line 9, in <module>
    print(eids[4])  #IndexErorr]
          ~~~~^^^
IndexError: list index out of range

F:\PYTHON FULL COURCE SUBJECT\CLASS-4 PYHTON DATA TYPE FUNCTION>